from model.ctr.afm import AFM
from model.ctr.autoInt import AutoInt
from model.ctr.deepfm import DeepFM
from model.ctr.flen import FLEN
from model.ctr.fm import FM
from model.ctr.fnn import FNN
from model.ctr.gbdt_lr import GBDTLR
from model.ctr.lr import LR
from model.ctr.nfm import NFM
from model.ctr.pnn import PNN
from model.ctr.wide_and_deep import WideAndDeep
